// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/pb/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for the Create Order method
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_pkg_pb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

// Response for the Create Order method
type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuscode    int64                  `protobuf:"varint,1,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_pkg_pb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetStatuscode() int64 {
	if x != nil {
		return x.Statuscode
	}
	return 0
}

// Order data
type OrderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MerchantId    string                 `protobuf:"bytes,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPaymentDone bool                   `protobuf:"varint,7,opt,name=is_payment_done,json=isPaymentDone,proto3" json:"is_payment_done,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserId        string                 `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderData) Reset() {
	*x = OrderData{}
	mi := &file_pkg_pb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderData) ProtoMessage() {}

func (x *OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderData.ProtoReflect.Descriptor instead.
func (*OrderData) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderData) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderData) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *OrderData) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderData) GetIsPaymentDone() bool {
	if x != nil {
		return x.IsPaymentDone
	}
	return false
}

func (x *OrderData) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Request for the Get Order method
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AddedBy       string                 `protobuf:"bytes,7,opt,name=added_by,json=addedBy,proto3" json:"added_by,omitempty"`
	Price         int64                  `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_pkg_pb_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *GetOrderRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetOrderRequest) GetAddedBy() string {
	if x != nil {
		return x.AddedBy
	}
	return ""
}

func (x *GetOrderRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// Response for the Get Order method
type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*OrderData           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Statuscode    int64                  `protobuf:"varint,2,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_pkg_pb_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderResponse) GetData() []*OrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetOrderResponse) GetStatuscode() int64 {
	if x != nil {
		return x.Statuscode
	}
	return 0
}

func (x *GetOrderResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Request for the Get by id Order method
type GetByIDOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDOrderRequest) Reset() {
	*x = GetByIDOrderRequest{}
	mi := &file_pkg_pb_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDOrderRequest) ProtoMessage() {}

func (x *GetByIDOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDOrderRequest.ProtoReflect.Descriptor instead.
func (*GetByIDOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetByIDOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetByIDOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// Response forl the Get by id Order method
type GetByIDOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *OrderData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Statuscode    int64                  `protobuf:"varint,2,opt,name=statuscode,proto3" json:"statuscode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDOrderResponse) Reset() {
	*x = GetByIDOrderResponse{}
	mi := &file_pkg_pb_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDOrderResponse) ProtoMessage() {}

func (x *GetByIDOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDOrderResponse.ProtoReflect.Descriptor instead.
func (*GetByIDOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetByIDOrderResponse) GetData() *OrderData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetByIDOrderResponse) GetStatuscode() int64 {
	if x != nil {
		return x.Statuscode
	}
	return 0
}

var File_pkg_pb_order_proto protoreflect.FileDescriptor

const file_pkg_pb_order_proto_rawDesc = "" +
	"\n" +
	"\x12pkg/pb/order.proto\x12\x05order\"\x94\x01\n" +
	"\x12CreateOrderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x03R\n" +
	"totalPrice\"5\n" +
	"\x13CreateOrderResponse\x12\x1e\n" +
	"\n" +
	"statuscode\x18\x01 \x01(\x03R\n" +
	"statuscode\"\xc4\x02\n" +
	"\tOrderData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\tR\n" +
	"merchantId\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12&\n" +
	"\x0fis_payment_done\x18\a \x01(\bR\risPaymentDone\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x03R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\"\xc4\x01\n" +
	"\x0fGetOrderRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12\x19\n" +
	"\badded_by\x18\a \x01(\tR\aaddedBy\x12\x14\n" +
	"\x05price\x18\b \x01(\x03R\x05price\"n\n" +
	"\x10GetOrderResponse\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.order.OrderDataR\x04data\x12\x1e\n" +
	"\n" +
	"statuscode\x18\x02 \x01(\x03R\n" +
	"statuscode\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"I\n" +
	"\x13GetByIDOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"\\\n" +
	"\x14GetByIDOrderResponse\x12$\n" +
	"\x04data\x18\x01 \x01(\v2\x10.order.OrderDataR\x04data\x12\x1e\n" +
	"\n" +
	"statuscode\x18\x02 \x01(\x03R\n" +
	"statuscode2\xda\x01\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12;\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponse\x12G\n" +
	"\fGetByIDOrder\x12\x1a.order.GetByIDOrderRequest\x1a\x1b.order.GetByIDOrderResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_order_proto_rawDescOnce sync.Once
	file_pkg_pb_order_proto_rawDescData []byte
)

func file_pkg_pb_order_proto_rawDescGZIP() []byte {
	file_pkg_pb_order_proto_rawDescOnce.Do(func() {
		file_pkg_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_order_proto_rawDesc), len(file_pkg_pb_order_proto_rawDesc)))
	})
	return file_pkg_pb_order_proto_rawDescData
}

var file_pkg_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_pb_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),   // 0: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 1: order.CreateOrderResponse
	(*OrderData)(nil),            // 2: order.OrderData
	(*GetOrderRequest)(nil),      // 3: order.GetOrderRequest
	(*GetOrderResponse)(nil),     // 4: order.GetOrderResponse
	(*GetByIDOrderRequest)(nil),  // 5: order.GetByIDOrderRequest
	(*GetByIDOrderResponse)(nil), // 6: order.GetByIDOrderResponse
}
var file_pkg_pb_order_proto_depIdxs = []int32{
	2, // 0: order.GetOrderResponse.data:type_name -> order.OrderData
	2, // 1: order.GetByIDOrderResponse.data:type_name -> order.OrderData
	0, // 2: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	3, // 3: order.OrderService.GetOrder:input_type -> order.GetOrderRequest
	5, // 4: order.OrderService.GetByIDOrder:input_type -> order.GetByIDOrderRequest
	1, // 5: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	4, // 6: order.OrderService.GetOrder:output_type -> order.GetOrderResponse
	6, // 7: order.OrderService.GetByIDOrder:output_type -> order.GetByIDOrderResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_order_proto_init() }
func file_pkg_pb_order_proto_init() {
	if File_pkg_pb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_order_proto_rawDesc), len(file_pkg_pb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_order_proto_goTypes,
		DependencyIndexes: file_pkg_pb_order_proto_depIdxs,
		MessageInfos:      file_pkg_pb_order_proto_msgTypes,
	}.Build()
	File_pkg_pb_order_proto = out.File
	file_pkg_pb_order_proto_goTypes = nil
	file_pkg_pb_order_proto_depIdxs = nil
}
