
syntax = "proto3";

package product;

option go_package = "./pkg/pb";

// Product service method 
service ProductService {

  // Create product
  rpc CreateProduct(CreateProductRequest) returns(CreateProductResponse);

  // Get Products
  rpc GetProduct(GetProductRequest) returns(GetProductResponse);

  // Get by id Products
  rpc GetByIDProduct(GetByIDProductRequest) returns(GetByIDProductResponse); 

  // Update product
  rpc UpdateProduct(UpdateProductRequest) returns(UpdateProductResponse);

  // Delete product
  rpc DeleteProduct(DeleteProductRequest) returns(DeleteProductResponse);
}

//Request for the Create Product method
message CreateProductRequest {
  string name=1;
  string description = 2;
  int64 quantity=3;
  string user_id=4;
  int64 price=5;
}

//Response for the Create Product method
message CreateProductResponse {
  int64 statuscode=1;
}

// Product data
message ProductData {
  string id=1;
  string name=2;
  string description = 3;
  int64 quantity=4;
  string added_by=5;
  int64 price=6;
  string created_at=7;
  string updated_at=8;
  string deleted_at=9;
}

//Request for the Get Product method
message GetProductRequest {
  string userid=1;
  int64 page=2;
  int64 limit=3;
  string id=4;
  string name=5;
  int64 quantity=6;
  string added_by=7;
  int64 price=8;
}

//Response for the Get Product method
message GetProductResponse {
  repeated ProductData data=1;
  int64 statuscode=2;
  int64 count = 3;
}

//Request for the Get by id Product method
message GetByIDProductRequest {
  string user_id=1;
  string product_id=2;
}

//Response for the Get by id Product method
message GetByIDProductResponse {
  ProductData data=1;
  int64 statuscode=2;
}

//Request for the Update Product method
message UpdateProductRequest {
  string userid=1;
  string product_id=2;
  ProductData data=3;
}

//Response for the Update Product method
message UpdateProductResponse {
  ProductData data=1;
  int64 statuscode=2;
}

//Request for the Delete Product method
message DeleteProductRequest {
  string user_id=1;
  string product_id=2;
}

//Response for the Delete Product method
message DeleteProductResponse {
  int64 statuscode=1;
}